substitutions:
  device_name: mini-ld2410

esphome:
  name: ${device_name}
  friendly_name: mini-ld2410
  on_boot:
    priority: -100
    then:
      - delay: 5s

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: debug

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 5min

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on

web_server:
  port: 80
  version: 3
  include_internal: true

uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO21
  baud_rate: 256000

ld2410:
  uart_id: ld2410_uart

binary_sensor:
  - platform: ld2410
    has_target:
      name: "LD2410 有人"
    has_moving_target:
      name: "LD2410 移动目标"
    has_still_target:
      name: "LD2410 静止目标"
  - platform: gpio
    name: "LD2410 GPIO16 人体"
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
    device_class: motion
    filters:
      - delayed_off: 3s

sensor:
  - platform: ld2410
    moving_distance:
      name: "LD2410 移动距离"
    still_distance:
      name: "LD2410 静止距离"
    moving_energy:
      name: "LD2410 移动能量"
    still_energy:
      name: "LD2410 静止能量"
    detection_distance:
      name: "LD2410 检测距离"

switch:
  - platform: ld2410
    engineering_mode:
      name: "LD2410 工程模式"
    bluetooth:
      name: "LD2410 传感器蓝牙"
      restore_mode: ALWAYS_OFF

button:
  - platform: ld2410
    query_params:
      name: "LD2410 查询参数"
    restart:
      name: "LD2410 传感器重启"
    factory_reset:
      name: "LD2410 出厂重置"

number:
  - platform: ld2410
    timeout:
      name: "LD2410 超时"
    max_move_distance_gate:
      name: "LD2410 最大移动距离门限"
    max_still_distance_gate:
      name: "LD2410 最大静止距离门限"
    light_threshold:
      name: "LD2410 光阈值"

text_sensor:
  - platform: ld2410
    version:
      name: "LD2410 固件版本"
    mac_address:
      name: "LD2410 蓝牙MAC"
